kind: project
metadata:
  name: odsc-west-2023
  created: '2023-10-26T00:57:05.861000'
spec:
  functions:
  - url: src/project_setup.py
    name: image-builder
    kind: job
    image: mlrun/mlrun:1.4.1
    handler: assert_build
  - url: src/functions/fine_tune.py
    name: fine-tune
    kind: job
    image: nschenone/odsc-west-2023-gpu:1.4.1
    handler: train
  - url: src/functions/get_pirate_dolly_data.py
    name: get-pirate-dolly-data
    kind: job
    image: nschenone/odsc-west-2023-cpu:1.4.1
    handler: get_pirate_dolly_data
  - url: src/functions/serving.py
    name: serving
    kind: serving
    image: nschenone/odsc-west-2023-gpu:1.4.1
    with_repo: true
  - url: src/functions/get_blog_data.py
    name: ingest-urls
    kind: job
    image: nschenone/odsc-west-2023-cpu:1.4.1
    handler: ingest_urls
    with_repo: true
  workflows:
  - path: src/workflows/main_workflow.py
    name: main
  - path: src/workflows/ingest_workflow.py
    name: ingest
  - path: src/workflows/tune_workflow.py
    name: tune
  artifacts: []
  conda: ''
  source: git://github.com/igz-us-sales/odsc-west-2023#master
  origin_url: git://github.com/igz-us-sales/odsc-west-2023.git#refs/heads/master
  load_source_on_run: true
  desired_state: online
  owner: nick
  default_image: .mlrun/func-odsc-west-2023-image-builder:latest
  build:
    image: .odsc-west-2023-gpu
    base_image: mlrun/ml-models-gpu:1.4.1
    commands: []
    requirements:
    - tqdm==4.66.1
    - arrr==1.0.4
    - peft==0.5.0
    - datasets==2.12.0
    - bitsandbytes==0.40.1
    - einops==0.6.1
    - trl==0.4.7
    - torch==2.0.1
    - accelerate==0.21.0
    - transformers==4.31.0
    - scipy==1.11.3
    - gradio==3.35.2
    - sentence-transformers==2.2.2
    - unstructured==0.7.12
    - pymilvus==2.3.0b1
    - langchain==0.0.324
  custom_packagers: []
status:
  state: online
